parameters:
#    expo_universidad.example.class: wikidemica\ExpoUniversidadBundle\Example

services:
#    expo_universidad.example:
#        class: %expo_universidad.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
