wikidemica\ExpoUniversidadBundle\Entity\Admin:
    type: entity
    table: ADMIN
    fields:
        idUsuario:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: id_usuario
            generator:
                strategy: IDENTITY
        nombre:
            type: string
            length: 45
            fixed: false
            nullable: false
        apellido:
            type: string
            length: 45
            fixed: false
            nullable: false
        celular:
            type: integer
            unsigned: false
            nullable: false
        telefono:
            type: integer
            unsigned: false
            nullable: true
    lifecycleCallbacks: {  }
