wikidemica\ExpoUniversidadBundle\Entity\Ciudad:
    type: entity
    table: CIUDAD
    fields:
        idCiudad:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: id_ciudad
            generator:
                strategy: IDENTITY
        nombre:
            type: string
            length: 60
            fixed: false
            nullable: false
        idRegion:
            type: integer
            unsigned: false
            nullable: false
            column: id_region
    lifecycleCallbacks: {  }
