wikidemica\ExpoUniversidadBundle\Entity\Colaborador:
    type: entity
    table: COLABORADOR
    fields:
        idUsuario:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: id_usuario
            generator:
                strategy: IDENTITY
    lifecycleCallbacks: {  }
