wikidemica\ExpoUniversidadBundle\Entity\InstitucionMultimedia:
    type: entity
    table: INSTITUCION-MULTIMEDIA
    fields:
        idMultimedia:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: id_multimedia
            generator:
                strategy: IDENTITY
        idInstitucion:
            type: integer
            unsigned: false
            nullable: false
            column: id_institucion
    lifecycleCallbacks: {  }
