wikidemica\ExpoUniversidadBundle\Entity\Institucion:
    type: entity
    table: INSTITUCION
    fields:
        idInstitucion:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: id_institucion
            generator:
                strategy: IDENTITY
        nombre:
            type: string
            length: 60
            fixed: false
            nullable: false
        linkPaginaWeb:
            type: text
            nullable: false
            column: link_pagina_web
        descripcion:
            type: text
            nullable: false
        idUniversidad:
            type: integer
            unsigned: false
            nullable: false
            column: id_universidad
    lifecycleCallbacks: {  }
