wikidemica\ExpoUniversidadBundle\Entity\MarkerInstitucion:
    type: entity
    table: MARKER-INSTITUCION
    fields:
        idMarker:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: id_marker
        idInstitucion:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: id_institucion
    lifecycleCallbacks: {  }
