wikidemica\ExpoUniversidadBundle\Entity\Multimedia:
    type: entity
    table: MULTIMEDIA
    fields:
        idMultimedia:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: id_multimedia
            generator:
                strategy: IDENTITY
        duracion:
            type: time
            nullable: false
        fechaPublicacion:
            type: date
            nullable: false
            column: fecha_publicacion
        descripcion:
            type: text
            nullable: true
        idUsuario:
            type: integer
            unsigned: false
            nullable: false
            column: id_usuario
        nombreCarpeta:
            type: string
            length: 65
            fixed: false
            nullable: false
            column: nombre_carpeta
    lifecycleCallbacks: {  }
