wikidemica\ExpoUniversidadBundle\Entity\Pais:
    type: entity
    table: PAIS
    fields:
        idPais:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: id_pais
            generator:
                strategy: IDENTITY
        nombre:
            type: string
            length: 60
            fixed: false
            nullable: false
        idContinente:
            type: integer
            unsigned: false
            nullable: false
            column: id_continente
    lifecycleCallbacks: {  }
