wikidemica\ExpoUniversidadBundle\Entity\Region:
    type: entity
    table: REGION
    fields:
        idRegion:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: id_region
            generator:
                strategy: IDENTITY
        nombre:
            type: string
            length: 60
            fixed: false
            nullable: false
        idPais:
            type: integer
            unsigned: false
            nullable: false
            column: id_pais
    lifecycleCallbacks: {  }
