wikidemica\ExpoUniversidadBundle\Entity\Universidad:
    type: entity
    table: UNIVERSIDAD
    fields:
        idUniversidad:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: id_universidad
            generator:
                strategy: IDENTITY
        nombre:
            type: string
            length: 45
            fixed: false
            nullable: false
        linkPaginaWeb:
            type: text
            nullable: false
            column: link_pagina_web
        publicaPrivada:
            type: boolean
            nullable: false
            column: publica_privada
        descripcion:
            type: text
            nullable: false
        idMarkerGoogleMap:
            type: integer
            unsigned: false
            nullable: false
            column: id_marker_google_map
        idCiudad:
            type: integer
            unsigned: false
            nullable: false
            column: id_ciudad
    lifecycleCallbacks: {  }
